# Generated by Django 2.2.8 on 2020-01-16 14:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_auto_20200113_2139'),
        ('social_element', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('elemental_fact_id', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('good_effect', models.TextField(blank=True)),
                ('bad_effect', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('remark', models.CharField(max_length=250)),
                ('status', models.CharField(default='active', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('trash', models.BooleanField(default=False)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='access.User')),
                ('social_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_element', to='social_element.Cl')),
            ],
        ),
    ]
