# Generated by Django 2.2.8 on 2020-01-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elemental_fact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl',
            name='correlation',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
