# Generated by Django 2.2.8 on 2020-01-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elemental_fact', '0002_cl_correlation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl',
            name='correlation',
            field=models.IntegerField(max_length=50),
        ),
    ]
