# Generated by Django 2.2.8 on 2020-01-17 08:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_auto_20200113_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog_id', models.CharField(max_length=50)),
                ('bolg_title', models.TextField(blank=True)),
                ('blog_txt', models.TextField(blank=True)),
                ('blog_file', models.FileField(blank=True, upload_to='')),
                ('status', models.CharField(default='inactive', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('trash', models.BooleanField(default=False)),
                ('blog_likes', models.ManyToManyField(blank=True, related_name='blog_likes', to='access.User')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_publisher', to='access.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.CharField(max_length=50)),
                ('comment_txt', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('trash', models.BooleanField(default=False)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.Cl')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_publisher', to='access.User')),
            ],
        ),
    ]
