# Generated by Django 2.2.8 on 2020-01-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cl',
            old_name='bolg_title',
            new_name='blog_title',
        ),
    ]
