# Generated by Django 2.2.4 on 2021-02-08 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_auto_20200113_2139'),
        ('social_element', '0001_initial'),
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('social_work_id', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('field_area', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('supervisor', models.CharField(max_length=250)),
                ('contact_no', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('trash', models.BooleanField(default=False)),
                ('social_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_social_element', to='social_element.Cl')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_work_user', to='access.User')),
                ('volunteer_id', models.ManyToManyField(blank=True, related_name='work_volunteer_id', to='volunteer.Cl')),
            ],
        ),
    ]
