# Generated by Django 2.2.8 on 2020-02-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correlation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cl',
        ),
    ]
